[package]
name = "mrgen"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.26", features = ["derive"] }
git2 = "0.19.0"
itertools = "0.13.0"
semver = "1.0.23"
